name: "Nix Flake"
on:
  push:
  pull_request:

jobs:
  build:
    name: "Builds"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - name: Build Flake
        run: nix build

  build_nixos_unstable:
    name: "Builds (on latest nixos-unstable)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - name: Build Flake
        run: |
          nix build \
            --override-input nixpkgs "github:NixOS/nixpkgs/nixos-unstable"
